# Generated by Django 3.2.6 on 2021-08-06 06:49

from django.db import migrations
from django.conf import settings


def add_groups(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    group(name="admin").save()
    group(name="investor").save()
    group(name="borrower").save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups)
    ]
